language: ruby
rvm:
- 2.1.0
script:
- RAILS_ENV=test bundle exec rake db:migrate && bundle exec rspec
before_script:
- psql -c 'create database bikeindex_test' -U postgres
env:
  global:
    secure: nFEP4tS5b44gE84jiZmcUebG6uflwYGwDyX2OR5vqVbYjFRqxwCUaLLUO98kga2KmzMsELQRpZz8mFWXMt9o37Fl0wbSJN574Mb/8z9kOZfUJutJOps2qYgbTgbAYNBnPPoFJIu2t2Dw6MOSRGgUguHmUV0gGEIeBInxZa23QOw=
